### ISSUE TITLE
Tests freezes at :app:testDebugUnitTest

### ISSUE THREAD

**Issue by williamwebb** [frogermcs/GithubClient#14]
`SplashActivityTests` never completes.

**Comment by maxim-pandra** [comment]
I have the same problem.
SplashActivityTest.testName() is never completes.

Everything else works. Thanks for sharing!

**Comment by GianpaMX** [comment]
I'm doing some refactors to this project and I have the same issue:
```
20:01:46.285 [DEBUG] [TestEventLogger] 
20:01:46.285 [DEBUG] [TestEventLogger] Gradle Test Executor 1 STARTED
20:01:46.291 [DEBUG] [TestEventLogger] 
20:01:46.291 [DEBUG] [TestEventLogger] frogermcs.io.githubclient.ui.activity.SplashActivityTests STARTED
20:01:46.384 [DEBUG] [TestEventLogger] 
20:01:46.384 [DEBUG] [TestEventLogger] frogermcs.io.githubclient.ui.activity.SplashActivityTests > testName STARTED
20:01:52.983 [null] [org.gradle.process.internal.health.memory.MemoryManager] 
20:01:52.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 16726704128, Free: 5753933824}
20:01:52.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 3717201920, Committed: 584056832}
20:01:57.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 16726704128, Free: 5630267392}
20:01:57.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 3717201920, Committed: 584056832}
20:02:02.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 16726704128, Free: 5595721728}
20:02:02.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 3717201920, Committed: 584056832}
20:02:07.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 16726704128, Free: 5567025152}
20:02:07.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 3717201920, Committed: 584056832}
20:02:12.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 16726704128, Free: 5553565696}
20:02:12.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 3717201920, Committed: 584056832}
20:02:17.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 16726704128, Free: 5543632896}
20:02:17.983 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 3717201920, Committed: 584056832}
<=20:02:21.641 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] Abort requested. Destroying process: Gradle Test Executor 1.
<============-> 96% EXECUTING [51s]
> :app:testDebugUnitTest > 0 tests completed
> :app:testDebugUnitTest > Executing test frogermcs.io.githubclient.ui.activity.SplashActivityTests
```

There is a similar issue [here](https://github.com/robolectric/robolectric/issues/3721) but I couldn't run `jstack`:
```
~ $ ps aux | grep java
...
juan     31982  166  3.7 6764628 617984 pts/2  Sl+  20:06   0:16 /opt/oracle-jdk-bin-1.8.0.152/bin/java -Djava.awt.headless=true -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /home/juan/.gradle/caches/4.1/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
...
```


```
~ $ jstack -l 31982 ~/asdf.txt 
Attaching to core /home/juan/asdf.txt from executable 31982, please wait...
Error attaching to core file: cannot open binary file
sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:286)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:673)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:156)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:191)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)

```
