### ISSUE TITLE
java.lang.VerifyError when run app

### ISSUE THREAD

**Issue by wqycsu** [frogermcs/GithubClient#18]
```
java.lang.VerifyError: frogermcs/io/githubclient/ui/activity/SplashActivity$AjcClosure1
                                                     at frogermcs.io.githubclient.ui.activity.SplashActivity.onCreate(SplashActivity.java:46)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)
```

Hi, when I build this project with gradle build tool 2.1.0 and run the app, I get the above error. But after reverting gradle to 2.0.0, this error disappear, I do not know why this happens.

**Comment by harichen** [comment]
me too.

**Comment by harichen** [comment]
@wqycsu 我也遇到这个问题，你解决了吗？

**Comment by wqycsu** [comment]
@harichen use gradle 2.0.0

**Comment by wanyt** [comment]
@harichen 把gradle的版本改成2.0.0就可以运行了。 I met this error too, and fix it by modify Android plugin version to 2.0.0.

**Comment by eddiecubed** [comment]
You can use the latest android plugin version (2.1.2) with this example.  You need to provide the `classpath`to Android metrics above the android build tools.  Also, you can only Debug the application.  This goes beyond if the `BuildConfig.DEBUG` is set to true or if the _debuggable_ flag is set to true in your manifest.

**Comment by feimengwang** [comment]
classpath 'com.android.tools.build:gradle:2.1.2'
I am using this, but I got the same error.

**Comment by feimengwang** [comment]
gradle 2.0.0 works for me

**Comment by eddiecubed** [comment]
What version of gradle was being used?  You would know this based on the distributionUrl in gradle-wrapper.properties
